### ISSUE TITLE
Can't choose the fiducial markers in drift correction plugin

### ISSUE THREAD

**Issue by Vertislav** [PALMsiever/palm-siever#15]
After import the rapidSTORM 3.3 localization data and running the Drift_correction_fiducial plugin I'm not able to choose the fiducial marker from the image. The area "Fiducial selection" in plugin is empty. Where is the problem with this plugin, or my localization data? Thank you for all your answers and advices.

Best regards,
Bartosz

**Comment by tp81** [comment]
Hi, thanks Bartosz for pointing out the problem. I just recreated the .fig. could you download the develop branch and see if the problem  is solved for you?

Cheers
Thomas

**Comment by Vertislav** [comment]
Thank you for your answer, Thomas. Unfortunately still is a problem, but different now:

Error using load
Unable to read MAT-file D:\Software\PalmSiever\palm-siever-140904\plugins\Drift_correction_fiducial.fig. Not a binary MAT-file.
Try LOAD -ASCII to read as text.

Error in matlab.graphics.internal.figfile.FigFile/read (line 36)
    hgDataVars = load(filename, '-mat', '-regexp', '^hg[M]');

Error in matlab.graphics.internal.figfile.FigFile (line 104)



Error in hgload (line 50)



Error in matlab.hg.internal.openfigLegacy (line 57)
    [fig, savedvisible] = hgload(filename, struct('Visible','off'));

Error in gui_mainfcn>local_openfig (line 286)
    gui_hFigure = matlab.hg.internal.openfigLegacy(name, singleton, visible);

Error in gui_mainfcn (line 158)
        gui_hFigure = local_openfig(gui_State.gui_Name, gui_SingletonOpt, gui_Visible);

Error in Drift_correction_fiducial (line 43)
    gui_mainfcn(gui_State, varargin{:});

Error in PALMsiever>plugins_callback (line 1731)
    feval(name,guidata(fig))

Error in PALMsiever>@(varargin)plugins_callback(name,varargin{:}) (line 1719)
        uimenu(mh,'Label',name,'Callback',@(varargin) plugins_callback(name,varargin{:}));
 
Error while evaluating Menu Callback

**Comment by tp81** [comment]
What version of MATLAB are you using? I saved the file with MATLAB 2014b, so it may be a backward compatibility problem. 

Cheers
Thomas

**Comment by Vertislav** [comment]
I'm using 2014b too.

Best,
Bartosz

**Comment by Vertislav** [comment]
Ok, it works!!! I suppose I pasted a wrong file to PALMsiever file. My fault.

Thank you so much for your help!

Best regards,
Bartosz

**Comment by tp81** [comment]
Great! Thanks! I will integrate it into the main branch then!

Cheers
Thomas
